-- Create views
CREATE OR REPLACE VIEW $DB_NAME$Views.User AS SELECT * FROM $DB_NAME$.User;
CREATE OR REPLACE VIEW $DB_NAME$Views.Contract AS SELECT * FROM $DB_NAME$.Contract;
CREATE OR REPLACE VIEW $DB_NAME$Views.Contract_Goal AS SELECT * FROM $DB_NAME$.Contract_Goal;
CREATE OR REPLACE VIEW $DB_NAME$Views.Contract_Party AS SELECT * FROM $DB_NAME$.Contract_Party;
CREATE OR REPLACE VIEW $DB_NAME$Views.NextId AS SELECT * FROM $DB_NAME$.NextId;

-- Sample view
CREATE OR REPLACE VIEW $DB_NAME$Views.t1 AS SELECT * FROM $DB_NAME$.t1;
